export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const SELECT_TITLE_ARTICLE = 'SELECT_TITLE_ARTICLE'

export const FILTER_DATE_ARTICLE = 'FILTER_DATE_ARTICLE'